Feature
BezzB/vetclinic pull request #1
Opened 2023-09-18 22:09 UTC by BezzB

This is a Vet clinic database: that involves the following  create animals table
Learning objectives
Create tables in SQL.
Insert and query data in SQL.
Description
In this project, I will use a relational database to create the initial data structure for a vet clinic. You will create a table to store animals' information, insert some data into it, and query it.

General requirements
Make sure that you used the correct [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).
Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
Project requirements
Use [this template](https://github.com/microverseinc/curriculum-template-databases) to generate your repo.
Create a database named vet_clinic.
Create a table named animals with the following columns:
id: integer
name: string
date_of_birth: date
escape_attempts: integer
neutered: boolean
weight_kg: decimal
Copy the SQL you used in the previous point into the schema.sql file in the generated repository.
Insert the following data:
Animal: His name is Agumon. He was born on Feb 3rd, 2020, and currently weighs 10.23kg. He was neutered and he has never tried to escape.
Animal: Her name is Gabumon. She was born on Nov 15th, 2018, and currently weighs 8kg. She is neutered and she has tried to escape 2 times.
Animal: His name is Pikachu. He was born on Jan 7th, 2021, and currently weighs 15.04kg. He was not neutered and he has tried to escape once.
Animal: Her name is Devimon. She was born on May 12th, 2017, and currently weighs 11kg. She is neutered and she has tried to escape 5 times.
Copy the SQL you used in the previous point into the data.sql file in the generated repository.
Write queries for the following quests:
Find all animals whose name ends in "mon".
List the name of all animals born between 2016 and 2019.
List the name of all animals that are neutered and have less than 3 escape attempts.
List the date of birth of all animals named either "Agumon" or "Pikachu".
List name and escape attempts of animals that weigh more than 10.5kg
Find all animals that are neutered.
Find all animals not named Gabumon.
Find all animals with a weight between 10.4kg and 17.3kg (including the animals with the weights that equals precisely 10.4kg or 17.3kg)
Take a screenshot of the results of your queries.
Copy the SQL you used in the previous point into the queries.sql file in the generated repository.
Remember to add the screenshot with the results of your queries to your Pull Request description.

2023-09-18 22:39 UTC, LionRouge1 requested changes
Hi @BezzB, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights
- Good PR
- Good commit
- All linters passed

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-18 22:39 UTC, LionRouge1 commented on README.md
>  ## 🚀 Live Demo <a name="live-demo"></a>
- [ ] Since this application is not deployed, kindly remove the **Live Demo** section to avoid having a broken link in your README file.

2023-09-18 22:39 UTC, LionRouge1 commented on README.md
>  ## 📝 License <a name="license"></a>
- [ ] The licence link is broken, kindly make sure the licence link is working that will make your project look more professional

2023-09-18 22:39 UTC, LionRouge1 requested changes
Hi @BezzB, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights
- Good PR
- Good commit
- All linters passed

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-19 08:08 UTC, AbelG101 approved these changes
![](https://media.giphy.com/media/eKfovWZOlOpbTDEX9F/giphy.gif)

# Hi @BezzB 👋, 

**Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 🥳🥇**

## Highlights
- Broken links have been removed from the readme body ✔

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-19 08:08 UTC, AbelG101 commented on README.md
- [ ] [OPTIONAL] The previous reviewer forgot to mention this but please make sure your readme looks professional, as I noticed you removed most of the major sections and some sections don't have enough description (like the getting started) and also make sure to remove all section descriptions as shown in the screenshot below 👇
  ![image](https://github.com/BezzB/vetclinic/assets/104968236/cf7a6ee2-d031-48ef-9bb0-dbec3ed14780)
  ![image](https://github.com/BezzB/vetclinic/assets/104968236/5291060c-4a7e-4bc9-a623-2467480a90ea)
- Please take these comments into consideration and work on them as soon as possible as it will lead to invalidations on your subsequent review requests.

2023-09-19 12:39 UTC, MahmoudBakr23 requested changes
Hello @BezzB 😃, 

Great work and effort you put into this project so far.

## Highlights 🚀 

There are some excellent points that you have made perfectly. Keep up! 💪
- Well done adding the queries so far
- Descriptive README file

However, there is always room for improvement.

> I'd like to remind you that your long hours of work are appreciated. However, the code review process is for improving your code, not criticizing it. 😄

 ## Required Changes ♻️

- [ ] Please attach screenshots of all the transactions in the PR summary
- [ ] Kindly note that this is another project you just made and submitted in the same PR as the previous one, so in the future, kindly ensure that each project is separated in a different PR so that we avoid conflicts and the review becomes easier

_Please check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

N/A

Cheers, and Happy coding!👏👨‍💻💻

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-19 12:39 UTC, MahmoudBakr23 commented on queries.sql
> +SELECT *
- [ ] Kindly make sure that you're following the project requirements which dictate that the species should be set to 'unspecified' and then rollbacked. Kindly revisit the requirements and implement the changes. See the example down below

```sql
UPDATE animals
   SET species = 'unspecified';

   SELECT species from animals;
   ROLLBACK;

   SELECT species from animals;
```

2023-09-19 16:00 UTC, merged