Vet clinic database: query multiple tables
BezzB/vetclinic pull request #3
Opened 2023-09-20 15:45 UTC by BezzB

Project requirements
Create a table named owners with the following columns:
id: integer (set it as autoincremented PRIMARY KEY)
full_name: string
age: integer
Create a table named species with the following columns:
id: integer (set it as autoincremented PRIMARY KEY)
name: string
Modify animals table:
Make sure that id is set as autoincremented PRIMARY KEY
Remove column species
Add column species_id which is a foreign key referencing species table
Add column owner_id which is a foreign key referencing the owners table
Remember all this goes in schema.sql file.
Insert the following data into the owners table:
Sam Smith 34 years old.
Jennifer Orwell 19 years old.
Bob 45 years old.
Melody Pond 77 years old.
Dean Winchester 14 years old.
Jodie Whittaker 38 years old.
Insert the following data into the species table:
Pokemon
Digimon
Modify your inserted animals so it includes the species_id value:
If the name ends in "mon" it will be Digimon
All other animals are Pokemon
Modify your inserted animals to include owner information (owner_id):
Sam Smith owns Agumon.
Jennifer Orwell owns Gabumon and Pikachu.
Bob owns Devimon and Plantmon.
Melody Pond owns Charmander, Squirtle, and Blossom.
Dean Winchester owns Angemon and Boarmon.
Remember these insertions and modifications happen in data.sql file.
Write queries (using JOIN) to answer the following questions:
What animals belong to Melody Pond?
List of all animals that are pokemon (their type is Pokemon).
List all owners and their animals, remember to include those that don't own any animal.
How many animals are there per species?
List all Digimon owned by Jennifer Orwell.
List all animals owned by Dean Winchester that haven't tried to escape.
Who owns the most animals?
Remember all these should be written in queries.sql file.
![Screenshot from 2023-09-20 17-52-33](https://github.com/BezzB/vetclinic/assets/118984781/0ae34752-e402-46dd-a9e3-ea95127c1273)
![Screenshot from 2023-09-20 18-28-48](https://github.com/BezzB/vetclinic/assets/118984781/ceb698a6-cac5-4d6d-abf9-25f52dcb0b9b)
![Screenshot from 2023-09-20 18-29-32](https://github.com/BezzB/vetclinic/assets/118984781/97d23994-2e07-4b52-9439-59aaa851a2ea)
![Screenshot from 2023-09-20 18-31-34](https://github.com/BezzB/vetclinic/assets/118984781/bb33e610-21db-4e3d-86d0-22a0f25656de)
![Screenshot from 2023-09-20 18-32-29](https://github.com/BezzB/vetclinic/assets/118984781/c0778529-33a3-40ff-97cd-669e75deda47)
![Screenshot from 2023-09-20 18-33-26](https://github.com/BezzB/vetclinic/assets/118984781/ac133a83-e1eb-4fd1-9595-ea318edb1ddd)
![Screenshot from 2023-09-20 18-34-48](https://github.com/BezzB/vetclinic/assets/118984781/6b75b7d5-d58c-4afd-9fcb-5008f820a598)
![Screenshot from 2023-09-20 18-35-52](https://github.com/BezzB/vetclinic/assets/118984781/d89838ef-0f67-434c-92ea-5ffcfcc01b9e)

2023-09-20 19:33 UTC, Bantealem requested changes
# Status: Change Required
Hi @BezzB, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [x] Professional Reame
- [x] Descriptive PR summary and title.
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] It would be better to make the branch name descriptive full since it will be more formal and clear for other developer.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-20 19:33 UTC, Bantealem commented on queries.sql
> +
Kindly that only the query that helps to analyze the data should be put in the `queries.sql` file. Currently, these are used to populate the table and should be put in the `data.sql` file according to the project requirement. Kindly, fix it.

![image](https://github.com/BezzB/vetclinic/assets/101523582/b6c30e18-ee63-475b-987d-e5abc6eb939c)

2023-09-20 19:33 UTC, Bantealem commented on queries.sql
> +);
Everything that changes the table structure should be put in the `schema .sql` file based on the project requremnt. Please  move these code to the `schema.sql` file.
![image](https://github.com/BezzB/vetclinic/assets/101523582/60d41c5f-8f46-41ec-a38c-8a601a86050a)

2023-09-21 00:02 UTC, Owusu-Desmond approved these changes
Hi @BezzB , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-21 06:07 UTC, merged